from curses import window
from typing import overload, TypeAlias, Literal
from enum import Enum

PadType: TypeAlias = window
ChType: TypeAlias = str | bytes | int

ESC = ...
BKSP = ...
ENTER = ...
CTRL_BKSP = ...

class Dir(Enum):
    UP = ...
    DOWN = ...
    LEFT = ...
    RIGHT = ...

class Align(Enum):
    LEFT = ...
    RIGHT = ...
    CENTER = ...

def draw_box(window: window, height: int, width: int, beg_y: int, beg_x: int): ...
def draw_button(window: window, height: int, width: int, beg_y: int, beg_x: int, text: str = "") -> None: ...
def reprint_win(window: window) -> None: ...
def lay(content: PadType, window: window) -> None: ...
@overload
def cover(window: window) -> None: ...
@overload
def cover(window: window, veil: PadType) -> None: ...
def uncover(window: window) -> None:...
@overload
def wprint(self, window: window, message: str) -> None: ...
@overload
def wprint(window: window, y: int, x: int, message: str) -> None: ...
@overload
def wread(window: window, message: str, speed: int = 1) -> None: ...
@overload
def wread(window: window, y: int, x: int, message: str, speed: int = 1) -> None: ...
def center(window: window, text: str) -> tuple[int, int]: ...

class _CurseWidget:
    def __init__(self): ...
    def __getattr__(self, name: str) -> object: ...
    def getmaxyx(self) -> tuple[int, int]: ...
    def getbegyx(self) -> tuple[int, int]: ...
    def refresh(self) -> None: ...
    def noutrefresh(self) -> None: ...
    @overload
    def chgat(self, attr: int) -> None: ...
    @overload
    def chgat(self, num: int, attr: int) -> None: ...
    @overload
    def chgat(self, y: int, x: int, attr: int) -> None: ...
    @overload
    def chgat(self, y: int, x: int, num: int, attr: int) -> None: ...
    @overload
    def addstr(self, str: str, attr: int = ...) -> None: ...
    @overload
    def addstr(self, y: int, x: int, str: str, attr: int = ...) -> None: ...
    @overload
    def addch(self, ch: ChType, attr: int = ...) -> None: ...
    @overload
    def addch(self, y: int, x: int, ch: ChType, attr: int = ...) -> None: ...

class Page(_CurseWidget): # pad based widget
    def __init__(self, parent: window, *, multiplier = 1, height = 0, width = 0): ...
    def out(self, text: str) -> None: ...
    def cls(self) -> None: ...
    def noutrefresh(self, pminrow: int, pmincol: int, sminrow: int, smincol: int, smaxrow: int, smaxcol: int) -> None: ...
    def shift(self, dir: Dir, unit: int = 1) -> None: ...
    def reset_offset(self) -> None: ...
    def get_offset(self) -> tuple[int, int]: ...

class Terminal(_CurseWidget):
    def __init__(self, nline: int, ncols: int, beg_y: int, beg_x: int): ...
    def proc_key(self, key: ChType) -> None: ...
    def clear_text(self) -> None: ...
    def get_text(self) -> str: ...
    def peek_text(self) -> str: ...

class TextBox:
    def __init__(self, nlines: int, ncols: int, text: str = "", \
                 alignment: Align = Align.LEFT, *, v_centered: bool = False): ...
    def set_text(self, text: str): ...
    def set_alignment(self, align: Align = None, *, v_centered: bool | None = None): ...
    def set_size(self, height: int, width: int): ...
    def print_textbox(self, parent: window, beg_y: int, beg_x: int): ...
    def read_textbox(self, parent: window, beg_y: int, beg_x: int,\
                     mode: Literal["WORD"] | Literal["CHAR"] = "CHAR", timeout: float = 0.05): ...

class Panel(_CurseWidget):
    def __init__(self, nline: int, ncols: int, beg_y: int, beg_x: int, *, outline: bool = False):
        self.visible: bool = ...
    def toggle(self) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def clear(self) -> None: ...

class Canvas(Panel):
    def __init__(self, nline: int, ncols: int, beg_y: int, beg_x: int, *, outline: bool = False, overlay = None): ...
    def set_overlay(self, overlay: PadType): ...
    def remove_overlay(self): ...