from curses import window
from _curses import _ChType

from typing import overload
from .consts import *

Pad = window

def draw_button(beg_y: int, beg_x: int, height: int, width: int, window: window, text: str = "") -> None: ...
def is_printable(char: _ChType) -> bool: ...
def reprint_win(window: window) -> None: ...
def lay(content: Pad, window: window) -> None: ...
@overload
def cover(window: window) -> None: ...
@overload
def cover(window: window, veil: Pad) -> None: ...
def uncover(window: window) -> None:...
@overload
def wprint(self, window: window, message: str): ...
@overload
def wprint(window: window, y: int, x: int, message: str): ...
@overload
def wread(window: window, message: str, speed: int = 1): ...
@overload
def wread(window: window, y: int, x: int, message: str, speed: int = 1): ...

class _CurseWidget:
    def __init__(self): ...
    def __getattr__(self, name: str): ...
    def getmaxyx(self) -> tuple[int, int]: ...
    def getbegyx(self) -> tuple[int, int]: ...
    def refresh(self) -> None: ...
    def noutrefresh(self) -> None: ...
    @overload
    def chgat(self, attr: int) -> None: ...
    @overload
    def chgat(self, num: int, attr: int) -> None: ...
    @overload
    def chgat(self, y: int, x: int, attr: int) -> None: ...
    @overload
    def chgat(self, y: int, x: int, num: int, attr: int) -> None: ...
    @overload
    def addstr(self, str: str, attr: int = ...) -> None: ...
    @overload
    def addstr(self, y: int, x: int, str: str, attr: int = ...) -> None: ...
    @overload
    def addch(self, ch: _ChType, attr: int = ...) -> None: ...
    @overload
    def addch(self, y: int, x: int, ch: _ChType, attr: int = ...) -> None: ...

class Console(_CurseWidget): # pad based widget
    def __init__(self, parent: window): ...
    def out(self, text: str): ...
    def cls(self): ...
    def noutrefresh(self, pminrow: int, pmincol: int, sminrow: int, smincol: int, smaxrow: int, smaxcol: int) -> None: ...

class TextBox(_CurseWidget):
    def __init__(self, nline, ncols, beg_y, beg_x): ...
    def proc_key(self, key: str): ...
    def clear_text(self): ...
    def get_text(self): ...

class Panel(_CurseWidget):
    def __init__(self, nline: int, ncols: int, beg_y: int, beg_x: int, outline = False): ...
    def show(self): ...
    def hide(self): ...
